version: "3"

services:
  backend:
    env_file: "./server/.env"
    build:
      context: ./server
      dockerfile: ./Dockerfile
    image: "haikuweather/server"
    ports:
      - "5000:5000"
  web:
    env_file: "./web/.env"
    build:
      context: ./web
      dockerfile: ./Dockerfile
    image: "haikuweather/web"
    ports:
      - "3000:3000"
    links:
      - "backend:be"
