/**
 * Generated by orval v6.18.1 🍺
 * Do not edit manually.
 * tsoa-example
 * OpenAPI spec version: 1.0.0
 */
import type { IWeatherReport } from './iWeatherReport';
import type { IWeatherSummary } from './iWeatherSummary';

export interface IGetWeatherResult {
  raw: IWeatherReport;
  summary: IWeatherSummary;
}
