/**
 * Generated by orval v6.18.1 🍺
 * Do not edit manually.
 * tsoa-example
 * OpenAPI spec version: 1.0.0
 */
import type { IGetWeatherResult } from './iGetWeatherResult';

export interface IGetWeatherReportResult {
  weather: IGetWeatherResult;
  imageUrl: string;
  poem: string;
}
