/**
 * Generated by orval v6.18.1 🍺
 * Do not edit manually.
 * tsoa-example
 * OpenAPI spec version: 1.0.0
 */

export type IWeatherReportSys = {
  sunset: number;
  sunrise: number;
  country: string;
  id: number;
  type: number;
};
