/**
 * Generated by orval v6.18.1 🍺
 * Do not edit manually.
 * tsoa-example
 * OpenAPI spec version: 1.0.0
 */

export * from './authorizationError';
export * from './createTemplate201';
export * from './createUser201';
export * from './fieldErrors';
export * from './getWeatherReportParams';
export * from './iGetWeatherReportResult';
export * from './iGetWeatherResult';
export * from './iOmittedUser';
export * from './iTemplate';
export * from './iWeatherReport';
export * from './iWeatherReportClouds';
export * from './iWeatherReportCoord';
export * from './iWeatherReportMain';
export * from './iWeatherReportRain';
export * from './iWeatherReportSnow';
export * from './iWeatherReportSys';
export * from './iWeatherReportWeatherItem';
export * from './iWeatherReportWind';
export * from './iWeatherSummary';
export * from './iWeatherSummaryCloud';
export * from './iWeatherSummaryHumidity';
export * from './iWeatherSummaryRain';
export * from './iWeatherSummarySnow';
export * from './iWeatherSummaryTemperature';
export * from './iWeatherSummaryVisibility';
export * from './iWeatherSummaryWind';
export * from './notFound';
export * from './omitIUserId';
export * from './pickITemplateContent';
export * from './pickIUserEmailOrPassword';
export * from './pickIUserExcludeKeyofIUserId';
export * from './userAuthorizationRequest';
export * from './userCreateRequest';
export * from './userLoginRequest';
export * from './validateError';