/**
 * Generated by orval v6.18.1 🍺
 * Do not edit manually.
 * tsoa-example
 * OpenAPI spec version: 1.0.0
 */

export interface IOmittedUser {
  /** The email the user used to register his account */
  email: string;
  /** The unique identifier provided by the API */
  id: string;
  firstName?: string;
  lastName?: string;
}
