/**
 * Generated by orval v6.18.1 🍺
 * Do not edit manually.
 * tsoa-example
 * OpenAPI spec version: 1.0.0
 */

export interface ITemplate {
  createdAt: string;
  updatedAt: string;
  id: string;
  userId: string;
  content: string;
}
