/**
 * Generated by orval v6.18.1 🍺
 * Do not edit manually.
 * tsoa-example
 * OpenAPI spec version: 1.0.0
 */

export type IWeatherSummaryCloud = typeof IWeatherSummaryCloud[keyof typeof IWeatherSummaryCloud];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const IWeatherSummaryCloud = {
  Clear: 'Clear',
  Some_clouds: 'Some clouds',
  Cloudy: 'Cloudy',
} as const;
