/**
 * Generated by orval v6.18.1 🍺
 * Do not edit manually.
 * tsoa-example
 * OpenAPI spec version: 1.0.0
 */

export type IWeatherSummarySnow = typeof IWeatherSummarySnow[keyof typeof IWeatherSummarySnow];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const IWeatherSummarySnow = {
  None: 'None',
  Light: 'Light',
  Moderate: 'Moderate',
  Heavy: 'Heavy',
  Very_heavy: 'Very heavy',
} as const;
