/**
 * Generated by orval v6.18.1 🍺
 * Do not edit manually.
 * tsoa-example
 * OpenAPI spec version: 1.0.0
 */

export type IWeatherSummaryHumidity = typeof IWeatherSummaryHumidity[keyof typeof IWeatherSummaryHumidity];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const IWeatherSummaryHumidity = {
  Dry: 'Dry',
  Humid: 'Humid',
  Very_humid: 'Very humid',
} as const;
