/**
 * Generated by orval v6.18.1 🍺
 * Do not edit manually.
 * tsoa-example
 * OpenAPI spec version: 1.0.0
 */

export type IWeatherSummaryRain = typeof IWeatherSummaryRain[keyof typeof IWeatherSummaryRain];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const IWeatherSummaryRain = {
  None: 'None',
  Light: 'Light',
  Moderate: 'Moderate',
  Heavy: 'Heavy',
  Very_heavy: 'Very heavy',
} as const;
