/**
 * Generated by orval v6.18.1 🍺
 * Do not edit manually.
 * tsoa-example
 * OpenAPI spec version: 1.0.0
 */

export type IWeatherSummaryTemperature = typeof IWeatherSummaryTemperature[keyof typeof IWeatherSummaryTemperature];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const IWeatherSummaryTemperature = {
  Freezing: 'Freezing',
  Cold: 'Cold',
  Chilly: 'Chilly',
  Warm: 'Warm',
  Hot: 'Hot',
  Very_hot: 'Very hot',
} as const;
