/**
 * Generated by orval v6.18.1 🍺
 * Do not edit manually.
 * tsoa-example
 * OpenAPI spec version: 1.0.0
 */

export type IWeatherSummaryVisibility = typeof IWeatherSummaryVisibility[keyof typeof IWeatherSummaryVisibility];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const IWeatherSummaryVisibility = {
  Clear: 'Clear',
  Fog: 'Fog',
  Misty: 'Misty',
  Haze: 'Haze',
} as const;
