/**
 * Generated by orval v6.18.1 🍺
 * Do not edit manually.
 * tsoa-example
 * OpenAPI spec version: 1.0.0
 */
import type { IWeatherSummaryTemperature } from './iWeatherSummaryTemperature';
import type { IWeatherSummaryHumidity } from './iWeatherSummaryHumidity';
import type { IWeatherSummaryVisibility } from './iWeatherSummaryVisibility';
import type { IWeatherSummaryWind } from './iWeatherSummaryWind';
import type { IWeatherSummaryCloud } from './iWeatherSummaryCloud';
import type { IWeatherSummaryRain } from './iWeatherSummaryRain';
import type { IWeatherSummarySnow } from './iWeatherSummarySnow';

export interface IWeatherSummary {
  temperature: IWeatherSummaryTemperature;
  humidity: IWeatherSummaryHumidity;
  weather: string;
  visibility: IWeatherSummaryVisibility;
  wind: IWeatherSummaryWind;
  cloud: IWeatherSummaryCloud;
  rain: IWeatherSummaryRain;
  snow: IWeatherSummarySnow;
}
