/**
 * Generated by orval v6.18.1 🍺
 * Do not edit manually.
 * tsoa-example
 * OpenAPI spec version: 1.0.0
 */

export type IWeatherSummaryWind = typeof IWeatherSummaryWind[keyof typeof IWeatherSummaryWind];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const IWeatherSummaryWind = {
  Calm: 'Calm',
  Light_breeze: 'Light breeze',
  Moderate_breeze: 'Moderate breeze',
  Strong_breeze: 'Strong breeze',
  Fresh_gale: 'Fresh gale',
  Strong_gale: 'Strong gale',
  Whole_gale: 'Whole gale',
  Storm: 'Storm',
  Hurricane: 'Hurricane',
} as const;
