/**
 * Generated by orval v6.18.1 🍺
 * Do not edit manually.
 * tsoa-example
 * OpenAPI spec version: 1.0.0
 */

export type IWeatherReportMain = {
  humidity: number;
  pressure: number;
  temp_max: number;
  temp_min: number;
  feels_like: number;
  temp: number;
};
