/**
 * Generated by orval v6.18.1 🍺
 * Do not edit manually.
 * tsoa-example
 * OpenAPI spec version: 1.0.0
 */

export type IWeatherReportWeatherItem = {
  icon: string;
  description: string;
  main: string;
  id: number;
};
