/**
 * Generated by orval v6.18.1 🍺
 * Do not edit manually.
 * tsoa-example
 * OpenAPI spec version: 1.0.0
 */
import type { PickIUserExcludeKeyofIUserId } from './pickIUserExcludeKeyofIUserId';

/**
 * Construct a type with the properties of T except for those in type K.
 */
export type OmitIUserId = PickIUserExcludeKeyofIUserId;
