/**
 * Generated by orval v6.18.1 🍺
 * Do not edit manually.
 * tsoa-example
 * OpenAPI spec version: 1.0.0
 */

/**
 * From T, pick a set of properties whose keys are in the union K
 */
export interface PickIUserExcludeKeyofIUserId {
  /** The email the user used to register his account */
  email: string;
  password: string;
  firstName?: string;
  lastName?: string;
}
