/**
 * Generated by orval v6.18.1 🍺
 * Do not edit manually.
 * tsoa-example
 * OpenAPI spec version: 1.0.0
 */
import type { PickIUserExcludeKeyofIUserId } from './pickIUserExcludeKeyofIUserId';

export type UserCreateRequest = PickIUserExcludeKeyofIUserId;
