/**
 * Generated by orval v6.18.1 🍺
 * Do not edit manually.
 * tsoa-example
 * OpenAPI spec version: 1.0.0
 */
import type { FieldErrors } from './fieldErrors';

export interface ValidateError {
  name: string;
  message: string;
  stack?: string;
  status: number;
  fields: FieldErrors;
}
